# Generated by Django 6.0.5 on 2026-05-06 20:05

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaContabil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('ATIVO', 'Ativo'), ('PASSIVO', 'Passivo'), ('RECEITA', 'Receita'), ('DESPESA', 'Despesa')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Encontro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('status', models.CharField(choices=[('PLANEJAMENTO', 'Em Planejamento'), ('ANDAMENTO', 'Em Andamento'), ('FINALIZADO', 'Finalizado')], default='PLANEJAMENTO', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Casal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('telefone_marido', models.CharField(blank=True, max_length=20)),
                ('telefone_esposa', models.CharField(blank=True, max_length=20)),
                ('associado', models.BooleanField(default=False, help_text='É um encontreiro associado ativo?')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Circulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cor', models.CharField(choices=[('AMARELO', 'Amarelo'), ('AZUL', 'Azul'), ('VERDE', 'Verde'), ('VERMELHO', 'Vermelho')], max_length=10)),
                ('casal_coordenador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='circulos_coordenados', to=settings.AUTH_USER_MODEL)),
                ('encontro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circulos', to='core.encontro')),
            ],
        ),
        migrations.CreateModel(
            name='EquipeTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('casais', models.ManyToManyField(related_name='equipes_trabalho', to=settings.AUTH_USER_MODEL)),
                ('encontro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipes', to='core.encontro')),
            ],
        ),
        migrations.CreateModel(
            name='FichaConvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_original', models.DecimalField(decimal_places=2, max_digits=10)),
                ('desconto_aplicado', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('valor_final', models.DecimalField(decimal_places=2, max_digits=10)),
                ('utilizada', models.BooleanField(default=False)),
                ('encontro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.encontro')),
                ('patrocinador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fichas_patrocinadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FichaInscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profissao_marido', models.CharField(max_length=100)),
                ('profissao_esposa', models.CharField(max_length=100)),
                ('local_trabalho_marido', models.CharField(blank=True, max_length=150)),
                ('local_trabalho_esposa', models.CharField(blank=True, max_length=150)),
                ('religiao_marido', models.CharField(max_length=50)),
                ('religiao_esposa', models.CharField(max_length=50)),
                ('casados_igreja', models.BooleanField(default=False)),
                ('alergias_marido', models.TextField(blank=True, help_text='Especifique alergias alimentares ou a medicamentos.')),
                ('alergias_esposa', models.TextField(blank=True, help_text='Especifique alergias alimentares ou a medicamentos.')),
                ('medicacao_uso_continuo', models.TextField(blank=True)),
                ('restricoes_alimentares', models.TextField(blank=True)),
                ('casal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ficha_inscricao', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MovimentacaoFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('descricao', models.CharField(max_length=255)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('encontro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='core.encontro')),
            ],
        ),
        migrations.CreateModel(
            name='LancamentoContabil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('D', 'Débito'), ('C', 'Crédito')], max_length=1)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.contacontabil')),
                ('movimentacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos', to='core.movimentacaofinanceira')),
            ],
        ),
    ]
