# Generated by Django 6.0.5 on 2026-05-06 20:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='circulo',
            name='casais',
            field=models.ManyToManyField(blank=True, related_name='circulos_participantes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fichainscricao',
            name='filhos_nomes_idades',
            field=models.TextField(blank=True, help_text='Nomes e idades dos filhos.'),
        ),
    ]
