# Generated by Django 6.0.5 on 2026-05-08 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_circulo_casais_fichainscricao_filhos_nomes_idades'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichainscricao',
            name='casados_igreja',
        ),
        migrations.AddField(
            model_name='casal',
            name='celular_esposa',
            field=models.CharField(blank=True, max_length=20, verbose_name='Celular da Esposa'),
        ),
        migrations.AddField(
            model_name='casal',
            name='celular_marido',
            field=models.CharField(blank=True, max_length=20, verbose_name='Celular do Marido'),
        ),
        migrations.AddField(
            model_name='fichainscricao',
            name='casados_civil_religioso',
            field=models.BooleanField(default=False, verbose_name='Casados no civil e/ou religioso'),
        ),
        migrations.AddField(
            model_name='fichainscricao',
            name='data_casamento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Casamento'),
        ),
        migrations.AddField(
            model_name='fichainscricao',
            name='data_nascimento_esposa',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento da Esposa'),
        ),
        migrations.AddField(
            model_name='fichainscricao',
            name='data_nascimento_marido',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento do Marido'),
        ),
        migrations.AddField(
            model_name='fichainscricao',
            name='nome_cracha_esposa',
            field=models.CharField(blank=True, help_text='Como a esposa gostaria de ser chamada durante o encontro.', max_length=80, verbose_name='Nome para o Crachá (Esposa)'),
        ),
        migrations.AddField(
            model_name='fichainscricao',
            name='nome_cracha_marido',
            field=models.CharField(blank=True, help_text='Como o marido gostaria de ser chamado durante o encontro.', max_length=80, verbose_name='Nome para o Crachá (Marido)'),
        ),
    ]
