# Generated by Django 6.0.5 on 2026-05-08 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_evangelical_fields_update'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fichainscricao',
            options={'ordering': ['encontro', 'numero_ficha'], 'verbose_name': 'Ficha de Inscrição', 'verbose_name_plural': 'Fichas de Inscrição'},
        ),
        migrations.AddField(
            model_name='casal',
            name='nome_esposa',
            field=models.CharField(blank=True, max_length=80, verbose_name='Nome da Esposa'),
        ),
        migrations.AddField(
            model_name='casal',
            name='nome_marido',
            field=models.CharField(blank=True, max_length=80, verbose_name='Nome do Marido'),
        ),
        migrations.AddField(
            model_name='fichainscricao',
            name='encontro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fichas_inscricao', to='core.encontro', verbose_name='Encontro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fichainscricao',
            name='numero_ficha',
            field=models.PositiveIntegerField(default=1, help_text='Numeração sequencial por encontro (começa em 1).', verbose_name='Nº da Ficha'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fichainscricao',
            name='casal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichas_inscricao', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='fichainscricao',
            unique_together={('encontro', 'casal'), ('encontro', 'numero_ficha')},
        ),
    ]
