# Generated by Django 6.0.5 on 2026-05-08 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_ficha_encontro_nomes'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichainscricao',
            name='ativa',
            field=models.BooleanField(default=True, help_text='Desmarque para desabilitar a ficha sem excluí-la.', verbose_name='Ficha Ativa'),
        ),
    ]
