# Generated by Django 6.0.5 on 2026-05-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_ficha_ativa'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichainscricao',
            name='endereco_bairro',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='fichainscricao',
            name='endereco_cep',
            field=models.CharField(blank=True, max_length=20, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='fichainscricao',
            name='endereco_cidade',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='fichainscricao',
            name='endereco_numero',
            field=models.CharField(blank=True, max_length=20, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='fichainscricao',
            name='endereco_rua',
            field=models.CharField(blank=True, max_length=150, verbose_name='Rua'),
        ),
        migrations.AddField(
            model_name='fichainscricao',
            name='endereco_uf',
            field=models.CharField(blank=True, max_length=2, verbose_name='UF'),
        ),
        migrations.AddField(
            model_name='fichainscricao',
            name='qtde_filhos',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantidade de Filhos'),
        ),
        migrations.AddField(
            model_name='fichainscricao',
            name='quem_fica_com_filhos',
            field=models.CharField(blank=True, max_length=150, verbose_name='Com quem ficarão os filhos durante o Encontro?'),
        ),
        migrations.AddField(
            model_name='fichainscricao',
            name='telefone_residencial',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefone Fixo/Residencial'),
        ),
        migrations.AddField(
            model_name='fichainscricao',
            name='tem_veiculo',
            field=models.BooleanField(default=False, verbose_name='Possui veículo?'),
        ),
    ]
