# Generated by Django 6.0.5 on 2026-05-08 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_novos_campos_ficha'),
    ]

    operations = [
        migrations.AddField(
            model_name='casal',
            name='perfil',
            field=models.CharField(blank=True, choices=[('', 'Selecione...'), ('PRESIDENTE', 'Presidente'), ('TESOUREIRO', 'Tesoureiro'), ('SECRETARIO', 'Secretário'), ('COORDENADOR', 'Coordenador de Encontro'), ('OUTROS', 'Outros')], max_length=20, verbose_name='Perfil na Diretoria'),
        ),
    ]
