# Generated by Django 6.0.5 on 2026-05-08 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_casal_perfil'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacontabil',
            options={'ordering': ['codigo']},
        ),
        migrations.AddField(
            model_name='contacontabil',
            name='codigo',
            field=models.CharField(default=1, help_text='Código da conta (ex: 1.0.0)', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacontabil',
            name='conta_pai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcontas', to='core.contacontabil'),
        ),
        migrations.AddField(
            model_name='contacontabil',
            name='nivel',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Nível 1'), (2, 'Nível 2'), (3, 'Nível 3 - Analítica')], default=1),
        ),
    ]
