# Generated by Django 6.0.5 on 2026-05-08 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_contacontabil_options_contacontabil_codigo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichainscricao',
            name='casal_convidou',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fichas_convidou', to=settings.AUTH_USER_MODEL, verbose_name='Casal que convidou'),
        ),
    ]
