# Generated by Django 6.0.5 on 2026-05-08 13:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_fichainscricao_casal_convidou'),
    ]

    operations = [
        migrations.AddField(
            model_name='encontro',
            name='valor_inscricao',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor da Inscrição'),
        ),
        migrations.AddField(
            model_name='fichaconvite',
            name='nome_casal_convidado',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nome do Casal Convidado'),
        ),
        migrations.AddField(
            model_name='fichaconvite',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
