# Generated by Django 6.0.5 on 2026-05-11 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_token_to_fichaconvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacontabil',
            name='natureza_da_conta',
            field=models.CharField(choices=[('D', 'Débito'), ('C', 'Crédito')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
